name: best_u
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  video_player: ^2.9.1
  cloud_firestore: ^5.6.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.0
  firebase_core: ^3.13.0
  google_sign_in: ^6.2.2
  skeletonizer: ^2.0.0
  app_links: ^6.1.4
  image_picker: ^1.1.2
  shared_preferences: ^2.3.5
  flutter_animate: ^4.5.2
  timezone: ^0.9.4
  path_provider: ^2.1.5
  flutter_local_notifications: ^17.2.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/welcom-logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/data/
    - assets/video/excercise-video.mp4
    - assets/video/exercises/
    - assets/sound/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
