// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoNRoI3K53axPR5pv4Iz0jHhGkaywan04',
    appId: '1:584745873347:web:99c7f758f59047e103d776',
    messagingSenderId: '584745873347',
    projectId: 'best-u-29f84',
    authDomain: 'best-u-29f84.firebaseapp.com',
    storageBucket: 'best-u-29f84.firebasestorage.app',
    measurementId: 'G-L20BJGNKDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTM5Bii-B7dVZhOM71TGB7zt6-wFUgjWI',
    appId: '1:584745873347:android:2bcddb7c65c1214d03d776',
    messagingSenderId: '584745873347',
    projectId: 'best-u-29f84',
    storageBucket: 'best-u-29f84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClu99jp-gpd4cmaqCRvkQ9xQPawnp49LI',
    appId: '1:584745873347:ios:ca3edc89a826beaa03d776',
    messagingSenderId: '584745873347',
    projectId: 'best-u-29f84',
    storageBucket: 'best-u-29f84.firebasestorage.app',
    iosBundleId: 'com.example.bestu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClu99jp-gpd4cmaqCRvkQ9xQPawnp49LI',
    appId: '1:584745873347:ios:ca3edc89a826beaa03d776',
    messagingSenderId: '584745873347',
    projectId: 'best-u-29f84',
    storageBucket: 'best-u-29f84.firebasestorage.app',
    iosBundleId: 'com.example.bestu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoNRoI3K53axPR5pv4Iz0jHhGkaywan04',
    appId: '1:584745873347:web:f5fb3adc4d170fcd03d776',
    messagingSenderId: '584745873347',
    projectId: 'best-u-29f84',
    authDomain: 'best-u-29f84.firebaseapp.com',
    storageBucket: 'best-u-29f84.firebasestorage.app',
    measurementId: 'G-4YTKNFBGEM',
  );
}
